### ISSUE TITLE
Sending whole memberMessageStatus list instead of individual event

### ISSUE THREAD

**Issue by DieGurke** [informatik-ag-ngl/envoy#1]
- [ ]  Modifying the `GroupMessageStatusChange` event to carry the whole memberMessageStatus list and not one individual change for only one member

- [ ]  Adapting the architecture on all three repositories to replace the memberStatuses that differ from the one that already exists or just override the whole list (but preferably the first option)

- [ ]  Making sure that the chaotic situation existing at the moment gets fixed

**Comment by delvh** [comment]
So, you want to enlarge the overhead both for the server and the client by hoping that this way you'll minimize it?
If I understand your issue correctly, every `GroupMessageStatusChange` received while being offline should be bundled into the list, which would be more efficient. On the other hand, every GroupMessageStatusChange received while being online would be less efficient.
Sooo... Should we just send the whole list of changed GroupMessageStatusChanges at once on login?
Or do I misinterpret something?

**Comment by CyB3RC0nN0R** [comment]
As far as I understand it, this would send the same status data, but compacted from multiple events to a single event containing a list. This is obviously not ideal, however we would need to know each status update timestamp for every member of the group to only deliver the correct status changes.
