### ISSUE TITLE
Restricting access to the LocalDB

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy#28]
If a client gets loaded in through a config with either wrong username or password ( -> the server does not recognize him), the `LoginScene` gets loaded with the localDB of the user whose login was unsuccessful.
If another user now logins via said LoginScene,  then he gains access to the **contacts and messages** of the old user (plus the one ones created/ received during said session).

How to prevent this:
Restrict access to LocalDBs, e. g. by
- [ ] password encrypt(-ing) the localDB

This is an example of this problem - the user `qwe` does not exist for the current server:
![grafik](https://user-images.githubusercontent.com/51889757/88378879-28230080-cda2-11ea-8912-41702865405c.png)

**Comment by CyB3RC0nN0R** [comment]
Any local data can be accessed without password protection when starting in offline mode. You could encrypt the user's database file using his password to prevent this.

**Comment by delvh** [comment]
With the original password or a hash of it?
