### ISSUE TITLE
Finishing new UI

### ISSUE THREAD

**Issue by DieGurke** [informatik-ag-ngl/envoy#36]
* implementing contact search mechanism into the `ChatScene`.
* implementing group creation mechanism into the `ChatScene`.

**Comment by delvh** [comment]
Finally!

I didn't think a day would come where you provide descriptions to your issues...

**Comment by DieGurke** [comment]
> Finally!
> 
> I didn't think a day would come where you provide descriptions to your issues...

I only missed out on that once so no right in beeing so harsh

**Comment by delvh** [comment]
I've counted it. You did not provide descriptions for 6/26 issues, which roughly equals a 23% rate for no descriptions. To be fair, it looked worse to me but still, 23% is not a value to be proud of as it means 1 out of 4 issues will not have a description.

**Comment by delvh** [comment]
As to not discriminate anyone I've also counted this ratio for me and @CyB3RC0nN0R:
My rate is 2.5/44 (5%),
CyB3RC0nN0R's is **0/55 (0%)**.

**Comment by DieGurke** [comment]
You have to much free time don't you 😂
