### ISSUE TITLE
Wrong scene size after popping scenes

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy#9]
**Describe the bug**
A scene shows in its preferred width and height, however the rest of the screen will be painted in pure (evil) white.

1. Open Envoy
2. Open any scene
3. Maximize scene
4. 'Pop' scene (back button)
5. Enjoy.

**Expected behavior**
a) the stage will have the size of the scene (stage gets minimized)
or
b) the stage will have the size of the scene (scene gets maximized - highly improbable)

![grafik](https://user-images.githubusercontent.com/51889757/85923263-19702900-b88a-11ea-97aa-8618e6ae5029.png)

**Comment by CyB3RC0nN0R** [comment]
We can work around this by switching the root node instead of the entire scene. Alternatively, a `StackPane` could be used. Maybe @DieGurke can work this into `f/new_ui`?

**Comment by delvh** [comment]
Not necessary anymore. Fixed it on `f/new_ui`. Now, this awful white screen will not be shown anymore. However, in the current implementation, scenes will automatically take their preferred sizes, meaning that when switching scenes, it is not uncommon that you end up with a totally different stage size than before.
